from turtle import Turtle,Screen
timmy = Turtle()
print(timmy)
timmy.shape("turtle")
timmy.color("cyan")
timmy.pensize(5)
timmy.forward(100)
timmy.right(90)
timmy.forward(100)
timmy.right(90)
timmy.forward(100)
timmy.right(90)
timmy.forward(100)
timmy.left(90)
timmy.pensize(10)
timmy.forward(100)
#timmy.up(100)
my_screen = Screen()
my_screen.canvheight = 800
print(my_screen.canvheight)
my_screen.exitonclick()